language: python
matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27
        dist: trusty
        sudo: false
      - python: 3.5
        env: TOX_ENV=py35
        dist: trusty
        sudo: false
      - python: 3.6
        env: TOX_ENV=py36
        dist: trusty
        sudo: false
      - python: 3.7
        env: TOX_ENV=py37
        dist: xenial
        sudo: true
      - python: 3.8
        env: TOX_ENV=py38
        dist: xenial
        sudo: false
      - python: 3.9
        env: TOX_ENV=py39
        dist: focal
        sudo: false
install:
    - pip install tox
    - pip install setuptools
    - pip install setuptools_scm
script:
    - tox -e $TOX_ENV
